server:
  port: 4040
  context-path: /sso1

# 监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

# org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter
security:
  oauth2:
    client:
      client-id: cloud  # 使用oauth认证机制时设置的授权 头信息Authorization=Bearer base64(client-id:client-secret)
      client-secret: gaz
      user-authorization-uri: http://localhost:3000/oauth/authorize
      access-token-uri: http://localhost:3000/oauth/token
      scope: server
    resource:
      jwt:
        key-uri: http://localhost:3000/oauth/token_key

spring:
  application:
    name: cloud-sso-client-demo
  profiles:
    active: dev
  redis:
    remote: true        # 是否是cachecloud 获取
    host: 192.168.0.200
    port: 6379
    password:

logging:
  config: classpath:logback.xml
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://gaz:han19951226@localhost:1025/eureka

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://gaz:han19951226@eureka:1025/eureka
