server:
  port: 9999

spring:
  rabbitmq:
    host: 192.168.0.200
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0

zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: cloud-auth,cloud-upms-service
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    cloud-auth:
      path: /auth/**
      serviceId: cloud-auth
      stripPrefix: true
      sensitiveHeaders:
    cloud-upms-service:
      path: /admin/**
      serviceId: cloud-upms-service
      stripPrefix: true
      sensitiveHeaders:
    cloud-tabe-service:
      path: /tabe/**
      serviceId: cloud-tabe-service
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    key-prefix: cloud-ratelimite 
    enabled: true 
    repository: REDIS 
    behind-proxy: true
    policies:
      cloud-upms-service:
        limit: 100
        quota: 100
        refresh-interval: 3

# Authorization=Bearer Base64(clientId:clientSecret)
security:
  validate:
    code: false
  sessions: stateless
  oauth2:
    client:
      client-id: pig
      client-secret: pig
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token
      service-id: cloud-gateway
      jwt:
         key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

urls:
  anon:
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/menu/userTree
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
       
logging:
  config: classpath:logback.xml
