server:
  port: 4000
jasypt:
  encryptor:
    password: lengleng
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

# datasoure默认使用JDBC
spring:
  redis:
    remote: true        # cachecloud 获取
    host: 192.168.0.200
    port: 6379
    password: 
  rabbitmq:
    host: 192.168.0.200
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0

# 分库分表支持
sharding:
  jdbc:
    defaultDataSourceName:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        jdbc-url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    # 实现日志根据主键的奇偶实现插入到sys_log_0，sys_log_1的表中. 
    # 实体的ID的生成策略，使用的mybatis-plus内置的雪花算法实现， IdType.ID_WORKER
    config:
      sharding:
        tables:
          # sys_log 分表策略
          sys_log:
            actual-data-nodes: ds.sys_log_${0..1}
            table-strategy:
              inline:
                sharding-column: id
                algorithm-expression: sys_log_${id % 2}
            key-generator-column-name: id
            
# mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.ngiveu.cloud.admin.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
fdfs:
  # 获取文件服务地址-nginx入口
  file-host: http://192.168.0.200:8888/
  # fdfs tracker-server 文件服务器上传地址
  tracker-list:
    - 192.168.0.200:22122
    
qiniu:
  accessKey: hM2cBDEM0FTYzpXbigRW90kV12NhhzhFM3jCzurJ
  secretKey: ENC(HM/K0KmtFoZSBhGDEA0Ez71ePTncZlQ954DfLNMZuOftKZq+2WR+dCXH9QEsf768q9wwd92RXLE=)
  bucket: cloud
  qiniuHost: http://p0hpm86wj.bkt.clouddn.com/
    
logging:
  config: classpath:logback.xml

