server:
  port: 9001
redis:
  cache:
    expiration: 3600
spring:
  rabbitmq:
    host: 192.168.0.200
    port: 5672 
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0
logging:
  config: classpath:logback.xml
# mybatis-plus配置,修改主键类型,mapper.xml/type别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.ngiveu.cloud.tabe.entity
  global-config:
    # 主键类型 0-数据库ID自增 1-用户输入ID 2-全局唯一ID(数字型) 3-全局唯一ID(UUID)
    id-type: 0
    # 字段策略 0-忽略判断 1-非NULL判断 2-非空判断
    field-strategy: 1
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper
    refersh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
# 分库分表支持
sharding:
  jdbc:
    defaultDataSourceName:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/tabe?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    datasource:
      names: ds
      ds:
        type: com.zaxx.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        jdbc-url: jdbc:mysql://127.0.0.1:3306/tabe?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false