server:
  port: 4001

spring:
  application:
    name: cloud-config-server
  profiles:
    active: dev, native # 配置文件本地化值为 native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
        # 配置文件本地化配置: server.native.search-locations: classpath:/config/ # 在resources/config下
        # 通过git托管配置文件
        # git:
        #  uri: https://gitee.com/DNGiveU/pig-config.git
        #  username: DNGiveU
        #  password: han19951226
# spring.profiles.active: native

---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://gaz:han19951226@localhost:1025/eureka
    registry-fetch-interval-seconds: 10

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://gaz:han19951226@eureka:1025/eureka
